apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: promop
  namespace: promop
  annotations:
    flux.weave.works/automated: "false"
    flux.weave.works/tag.chart-image: semver:~0
spec:
  releaseName: promop
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com/
    name: prometheus-operator
    version: 5.15.0
  values:
    # The following config is necessary for AWS EKS:
    # Not monitoring etcd, kube-scheduler, or kube-controller-manager because it is managed by EKS
    # coreDns:
    #   service:
    #     selector:
    #       k8s-app: kube-dns
    # defaultRules:
    #   rules:
    #     etcd: false
    #     kubeScheduler: false
    # kubeControllerManager:
    #   enabled: false
    # kubeEtcd:
    #   enabled: false
    # kubeScheduler:
    #   enabled: false
    # end AWS EKS config

    # this is needed for minikube
    kubelet:
      serviceMonitor:
        https: false

    kubeEtcd:
      service:
        selector:
          k8s-app: null
          component: etcd

    grafana:
      sidecar:
        dashboards:
          enabled: true
          searchNamespace: ALL
    prometheus:
      prometheusSpec:
        replicas: 1
        ruleNamespaceSelector:
          any: true
        serviceMonitorSelector:
          monitoring: promop
        serviceMonitorNamespaceSelector:
          any: true