---
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: grpcdemo-server
  namespace: grpcdemo
spec:
  values:
    replicaCount: 2
---
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: promop
  namespace: promop
spec:
  values:
    prometheus:
      prometheusSpec:
        replicas: 3